######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 9 23:49:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
FORMS += mydialog.ui
SOURCES += main.cpp mydialog.cpp
