######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 8 05:00:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += printtext.h
SOURCES += main.cpp printtext.cpp
